name: urm.urm@URM
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

loops: 16
num_layers: 8

hidden_size: 512
num_heads: 8
expansion: 4

H_cycles: 4
L_cycles: 3

loop_deltas: [0, 8]

puzzle_emb_ndim: ${.hidden_size}
pos_encodings: rope

# Enable timing profile output during training for debugging
profile: true

eval_interval: 1000
checkpoint_every_eval: True
checkpoint_path: /volume/ylchen/code/loop_arcagi/checkpoints/v22_debug

ema: True
ema_rate: 0.999
